---
name: Prepare deployment
description: Hello
inputs:
  project-alias:
    description: the project alias for the project you are running a deployment on
    required: true
  api-key:
    description: key needed to have access to api
    required: true
outputs:
  DEPLOYMENT_ID:
    description: The deployment id to be used by the rest of the process
runs:
  using: node16
  main: dist/index.js